# Generated by Django 5.2.1 on 2025-07-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('vatcode', models.CharField(max_length=10)),
                ('stdsell', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
