# Generated by Django 5.2.1 on 2025-07-28 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_stdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('opening', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pump', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diesel_opening', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diesel_closing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diesel_pump', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unredeemed_vouchers', models.IntegerField()),
                ('unredeemed_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('redeemed_vouchers', models.IntegerField()),
                ('redeemed_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('drop_sports', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drop_lotto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drop_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drop_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drop_sugar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drop_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atm', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
