# Generated by Django 5.2.1 on 2025-08-14 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dailycashup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCashUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fuel_type', models.CharField(choices=[('UNLEADED 95', 'UNLEADED 95'), ('DIESEL 50PPM', 'DIESEL 50PPM')], max_length=20)),
                ('opening_litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('litres_pumped', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyCashUp',
        ),
    ]
