# Generated by Django 5.2.5 on 2025-10-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_forecourtinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('unleaded_95_opening', models.FloatField(default=0)),
                ('unleaded_95_closing', models.FloatField(default=0)),
                ('diesel_50_opening', models.FloatField(default=0)),
                ('diesel_50_closing', models.FloatField(default=0)),
                ('dispensed_ulp_95', models.FloatField(default=0)),
                ('dispensed_d50', models.FloatField(default=0)),
                ('rate_r22_12', models.FloatField(default=0)),
                ('rate_r23_36', models.FloatField(default=0)),
                ('pumped_theoretical', models.FloatField(default=0)),
                ('actual_pos', models.FloatField(default=0)),
                ('variance_pos', models.FloatField(default=0)),
                ('cash', models.FloatField(default=0)),
                ('cards', models.FloatField(default=0)),
                ('actual_sales', models.FloatField(default=0)),
                ('variance_sales', models.FloatField(default=0)),
                ('expenses', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('over_short', models.FloatField(default=0)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
