# Generated by Django 5.2.5 on 2025-10-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_dailysalereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_r22_12', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate_r23_36', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='dailysalereport',
            table='daily_sales_reports',
        ),
    ]
