# Generated by Django 4.2.26 on 2025-12-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_inventory_product_delete_return_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('slip_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('trandate', models.DateField()),
                ('trantime', models.TimeField()),
                ('logfile', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqno', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=50)),
                ('qty', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('vat', models.FloatField()),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.slip')),
            ],
        ),
    ]
