# Generated by Django 4.2.26 on 2025-12-01 20:11

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_slip_slipitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slipitem',
            old_name='slip',
            new_name='slip_id',
        ),
        migrations.RemoveField(
            model_name='slip',
            name='logfile',
        ),
        migrations.AddField(
            model_name='slip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True),
        ),
        migrations.AddField(
            model_name='slip',
            name='opref',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='slip',
            name='termnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slipitem',
            name='attendant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slipitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True),
        ),
        migrations.AddField(
            model_name='slipitem',
            name='opref',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='slipitem',
            name='raw_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='slipitem',
            name='termnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slipitem',
            name='trandate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slipitem',
            name='trantime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slipitem',
            name='userid',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='slip',
            name='slip_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slip',
            name='userid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slipitem',
            name='item_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slipitem',
            name='item_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slipitem',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slipitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slipitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slipitem',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
