# Generated by Django 4.2.26 on 2025-12-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_slip_slipitem_slip_id_remove_slip_logfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='slip',
            name='opref',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slip',
            name='termnum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='slipitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='slipitem',
            name='opref',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slipitem',
            name='raw_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slipitem',
            name='termnum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='slipitem',
            name='trandate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='slipitem',
            name='trantime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slipitem',
            name='userid',
            field=models.TextField(),
        ),
    ]
