# Generated by Django 4.2.26 on 2025-12-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_slip_created_at_alter_slip_opref_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slip',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='slipitem',
            options={'managed': False},
        ),
    ]
