# Generated by Django 4.2.26 on 2025-12-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_slip_options_alter_slipitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slip',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='slipitem',
            options={'managed': True},
        ),
    ]
