# Generated by Django 5.2.8 on 2025-12-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_slip_options_alter_slipitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slip',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='slipitem',
            options={'managed': False},
        ),
    ]
