# Generated by Django 5.2.8 on 2026-01-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_slip_options_alter_slipitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='slip',
            table='slips',
        ),
        migrations.AlterModelTable(
            name='slipitem',
            table='slip_items',
        ),
    ]
